name: Deploy

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: create new ssh server
        run: |
              apt-get update && apt-get install -y openssh-client 
              eval $(ssh-agent -s)
              echo "{{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
              mkdir -p ~/.ssh
              chmod 700 ~/.ssh
              echo "{{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-keyscan -p ${{ secrets.SSH_PORT}} {{ secrets.IP_SERVER }} >> ~/.ssh/known_hosts
              chmod 644 ~/.ssh/known_hosts
              '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

      - name: ssh ke vps
        run: |
              ssh -p ${{ vars.SSH_PORT}} ${{ vars.VAR_USER }}@${{ secrets.IP_SERVER }} "docker ps -a"
              echo "Deploy Berhasil"
#ssh -p ${{ env.SSH_PORT}} ${{ env.VAR_USER }}@${{ vars.IP_SERVER }} "cd ${{ env.VAR_DIREKTORI }} && git pull https://${{ env.GIT_USER}}:${{ vars.TOKEN}}@${{ env.VAR_GIT_URL_TANPA_HTTP}} main && exit"

    # - ls -lah ~/.ssh  # Cek apakah file id_rsa ada
    # - cat ~/.ssh/id_rsa  # Cek apakah key tersimpan dengan benar (hapus di output log agar aman)
    # - ssh-keygen -y -f ~/.ssh/id_rsa  # Cek apakah bisa mengekstrak public key
              


