name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PORT: ${{ vars.SSH_PORT }}
          IP_SERVER: ${{ secrets.IP_SERVER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "$SSH_PORT" "$IP_SERVER" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: SSH ke VPS
        env:
          SSH_PORT: ${{ vars.SSH_PORT }}
          VAR_USER: ${{ vars.VAR_USER }}
          IP_SERVER: ${{ secrets.IP_SERVER }}
          TOKEN: ${{ secrets.TOKEN }}
          VAR_DIREKTORI: ${{ vars.VAR_DIREKTORI }}
          GIT_USER: ${{ vars.GIT_USER }}
          VAR_GIT_URL_TANPA_HTTP: ${{ vars.VAR_GIT_URL_TANPA_HTTP }}

        run: |
          ssh -p "$SSH_PORT" "$VAR_USER@$IP_SERVER" "cd $VAR_DIREKTORI && git pull https://$GIT_USER:$TOKEN@$VAR_GIT_URL_TANPA_HTTP main && exit"
          echo "Deploy Berhasil"
